---
title: "More detailed analysis"
author: "Kent Riemondy RBI"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "html") })
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: cosmo
    highlight: tango
    fig_caption: true
    code_folding: hide
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = FALSE)
```


```{r libs, message=FALSE, warning=FALSE, echo=FALSE}
source(here::here("R", "utils.R"))

walk(c(fig_dir, mkrs_dir, tbls_dir, obj_dir),
     dir.create, showWarnings = F)

seed_value <- 20200824
```


```{r}
so <- qread(file.path(obj_dir, "so.qs"))
```

## Rename goblet to mucin club cells

```{r}
so$coarse_cell_type <- ifelse(so$coarse_cell_type == "goblet cells", 
                              "mucin club cells",
                              so$coarse_cell_type)

so$cell_type_cluster <- ifelse(so$cell_type_cluster == "goblet cells (6)", 
                              "mucin club cells (6)",
                              so$cell_type_cluster)
```
## Differential expression between elastase and saline conditions

```{r}
clusters <- unique(so@meta.data$cell_type_cluster)
treatment <- as.character(unique(so@meta.data$treatment))
so_tmp <- so
so_tmp$cluster_treatment <- str_c(so$treatment, "_", so$cell_type_cluster)

de_res <- map(clusters, ~{
    to_test <- str_c(treatment, "_", .x)
    wilcoxauc(so_tmp, "cluster_treatment", groups_use = str_c(treatment, "_", .x)) %>% 
      filter(group == to_test[1]) %>% 
        arrange(desc(logFC))
  })

de_sig_res <- map(de_sig_res, ~filter(.x, padj < 0.05) %>% 
                    arrange(desc(logFC)))
names(de_sig_res) <- clusters

de_res <- c(list(Description = scbp::presto_marker_description()), de_res)
openxlsx::write.xlsx(de_res, file.path("tables", "Elastase_v_Saline_per_cell_type.xlsx"))

de_sig_res <- c(list(Description = scbp::presto_marker_description()), de_sig_res)
openxlsx::write.xlsx(de_sig_res, file.path("tables", "Elastase_v_Saline_per_cell_type_significant.xlsx"))
```


```{r}
map(clusters, ~{
  so_tmp <- subset(so, subset = cell_type_cluster == .x)
  plot_cell_proportions(so_tmp,
                        sample_id = "treatment",
                        group_id =  "Phase", 
                        cols =  palette_OkabeIto) +
    labs(title = .x)
})
```
Also write out table cell counts

```{r}
get_cell_count_matrix(so, "cell_type_cluster", "treatment") %>% 
  rownames_to_column("cell_type") %>% 
  mutate(Percent_Saline = 100 * (Saline / sum(Saline)),
         Percent_Elastase = 100 * (Elastase / sum(Elastase))
         ) %>% 
  write_csv(file.path(tbls_dir, "cell_counts_per_treatment_cell_type.csv"))


```
# Various analyses requested

```{r}
umaps <- plot_umap(so, 
          c("Muc5b", "Muc5ac"), 
          group = "treatment")
p <- plot_grid(plotlist = umaps, nrow = 2, ncol = 1)

save_plot(file.path(fig_dir, "muc5ac_muc5b_umaps.pdf"), 
          p, nrow = 2, ncol = 1, 
          base_aspect_ratio = 1.75)
p

```

```{r}
p <- plot_umap(so, 
          "Krt8", 
          group = "treatment")

save_plot(file.path(fig_dir, "Krt8_umap.pdf"), 
          p, 
          base_aspect_ratio = 1.75)
p

```

```{r}
p <- plot_umap(so, 
          "egfp-sv40", 
          group = "treatment")

save_plot(file.path(fig_dir, "Wnt-egfp-sv40_umap.pdf"), 
          p, 
          base_aspect_ratio = 1.75)
p

```

```{r}
vln <- plot_violins(so, 
                    "cell_type_cluster", 
                    split_by = "treatment",
                    c("Muc5b", "Muc5ac")) + 
  labs(x = "", y = "Expression")
vln

save_plot(file.path(fig_dir, "muc5ac_muc5b_vln_plots.pdf"), 
          vln,
          base_height = 5,
          base_aspect_ratio = 1.5)

```

## Examine ATII cluster markers

```{r}
so_at2 <- subset(so, subset = coarse_cell_type == "AT2 cells" )
at2_markers <- wilcoxauc(so_at2, "cell_type_cluster") %>% 
  filter(padj < 0.05,
         pct_in > 10) %>% 
  group_by(group) %>% 
  arrange(padj, .by_group = TRUE)

write_markers_xlsx(split(at2_markers, at2_markers$group),
                     file.path(tbls_dir, "at2_cluster_differential_expression.xlsx"),
                   description_string = "Genes differentially expressed between each AT2 cluster versus the other AT2 clusters")
```

## Examine mucin cells

```{r}
so_club <- subset(so, subset = coarse_cell_type %in% c("club cells", "mucin club cells"))

so_club <- FindVariableFeatures(so_club) %>% 
  ScaleData(.) %>% 
  RunPCA(.) %>% 
  FindNeighbors(., 
                reduction = "pca", 
                dims = 1:10, 
                k.param = 10L, 
                verbose = FALSE) %>% 
  FindClusters(.,
               resolution = seq(0.1, 2, 0.1),
               random.seed = seed_value,
               verbose = FALSE) %>% 
  RunUMAP(., 
          dims = 1:10,
          n.neighbors = 10L,
          min.dist = 0.5, 
          seed.use = seed_value,
          verbose = FALSE)

cluster_cols <- str_subset(colnames(so_club@meta.data), "RNA_snn.res")

plot_umap(so_club, 
          cluster_cols, 
          pt_size = 1,
          label_text = TRUE, 
          label_color = "black",
          ggrepel_opts = list(force = 0)) 
```

```{r}
plts <- plot_umap(so_club, 
          c("RNA_snn_res.0.3",
            "Muc5b",
            "Muc5ac"),
          group = "treatment",
          pt_size = 1)

p <- plot_grid(plotlist = plts, nrow = 3, ncol = 1)
save_plot(file.path(fig_dir, "club_cells_reclustered.pdf"), 
          p,
          nrow = 3,
          ncol = 1)
p
```

```{r}
library(ggridges)
so_mucin <- subset(so_club, subset = coarse_cell_type == "mucin club cells")

p <- get_metadata(so_mucin, c("Muc5b", "Muc5ac")) %>% 
  ggplot(aes(Muc5b, treatment)) +
    geom_density_ridges(aes(fill = treatment)) + 
  scale_fill_manual(values = palette_OkabeIto) +
  theme_ridges() +
  theme(legend.position = "none")
    
p2 <- get_metadata(so_mucin, c("Muc5b", "Muc5ac")) %>% 
  ggplot(aes(Muc5ac, treatment)) +
    geom_density_ridges(aes(fill = treatment)) + 
  scale_fill_manual(values = palette_OkabeIto) +
  theme_ridges() +
  theme(legend.position = "none")

p <- plot_grid(p, p2, nrow = 2)
save_plot(file.path(fig_dir, "club_cells_muc5b_muc5ac.pdf"), 
          p,
          nrow = 2,
          ncol = 1,
          base_asp = 1.4)
p
```


## correlated genes to mucin genes

```{r}

to_check <- c("Retnla",
  "Pigr",
  "Sec14l3",
  "Ahnak",
  "Sfn",
  "Fcgbp",
  "Krt8",
  "Muc5b",
  "Muc5ac")


dat <- get_metadata(so_mucin, to_check, embedding = NULL) %>% 
  select(treatment, Retnla:Muc5ac) %>% 
  mutate(treatment = factor(treatment, levels = c("Saline", "Elastase")))

elast <- filter(dat, treatment == "Elastase")
saline <- filter(dat, treatment == "Saline")

plts <- map(to_check[1:7], ~{
  
  bplot <- ggplot(dat, aes_string("treatment", .x)) +
    geom_boxplot(aes(fill = treatment)) +
    geom_jitter() +
    scale_fill_manual(values = palette_OkabeIto) +
    labs(x = "") +
    theme(legend.position = "none")
    
  
  splts <- map(c("Muc5b", "Muc5ac"),
      function(x){
        ecor <- cor(elast[[.x]], elast[[x]], method = "spearman")
        scor <- cor(saline[[.x]], saline[[x]], method = "spearman")
        
        text_df <- tibble(
          treatment = factor(c("Saline", "Elastase"),levels = c("Saline", "Elastase")),
          pearson = str_c("r = ", signif(c(scor, ecor), 3))
        )
        p <- ggplot(dat, aes_string(.x, x)) +
          geom_point(aes(color = treatment)) +
          facet_wrap(~treatment) +
          geom_text(data = text_df,
                    aes(x = -Inf, y = -Inf, label = pearson),
                    hjust   = -.5,
                    vjust   = -20) +
          scale_color_manual(values = palette_OkabeIto) +
    theme(legend.position = "none")
        p
      })
  plot_grid(plotlist = c(list(bplot), splts),
            ncol = 3,
            nrow = 1, rel_widths = c(0.2, 0.4, 0.4))
})

p <- plot_grid(plotlist = plts, 
               nrow = length(plts),
               ncol = 1)
save_plot("cor_to_mucins.pdf", 
          p,
          base_asp = 3,
          nrow = length(plts),
          ncol = 1)
p
```

Run for all genes


```{r}
to_check <- rownames(so_mucin)[rowSums(so_mucin@assays$RNA@data > 0 ) > 5]
all_data <- get_metadata(so_mucin, to_check, embedding = NULL) %>% 
  mutate(treatment = factor(treatment, levels = c("Saline", "Elastase")))

elast <- filter(all_data, treatment == "Elastase")
saline <- filter(all_data, treatment == "Saline")

cor_values <- map_dfr(to_check, ~{
  tibble(
    gene = .x,
    elastase_muc5b = cor(elast[[.x]], elast[["Muc5b"]], method = "spearman"),
    saline_muc5b = cor(saline[[.x]], saline[["Muc5b"]], method = "spearman"),
    elastase_muc5ac = cor(elast[[.x]], elast[["Muc5ac"]], method = "spearman"),
    saline_muc5ac = cor(saline[[.x]], saline[["Muc5ac"]], method = "spearman"))
  }) %>% 
  arrange(desc(elastase_muc5b)) 


plts <- map(cor_values$gene[2:11], ~{
  
  bplot <- ggplot(all_data, aes_string("treatment", .x)) +
    geom_boxplot(aes(fill = treatment)) +
    geom_jitter() +
    scale_fill_manual(values = palette_OkabeIto) +
    labs(x = "") +
    theme(legend.position = "none")
    
  
  splts <- map(c("Muc5b", "Muc5ac"),
      function(x){
        ecor <- cor(elast[[.x]], elast[[x]], method = "spearman")
        scor <- cor(saline[[.x]], saline[[x]], method = "spearman")
        
        text_df <- tibble(
          treatment = factor(c("Saline", "Elastase"),levels = c("Saline", "Elastase")),
          pearson = str_c("r = ", signif(c(scor, ecor), 3))
        )
        p <- ggplot(all_data, aes_string(.x, x)) +
          geom_point(aes(color = treatment)) +
          facet_wrap(~treatment) +
          geom_text(data = text_df,
                    aes(x = -Inf, y = -Inf, label = pearson),
                    hjust   = -.5,
                    vjust   = -20) +
          scale_color_manual(values = palette_OkabeIto) +
    theme(legend.position = "none")
        p
      })
  plot_grid(plotlist = c(list(bplot), splts),
            ncol = 3,
            nrow = 1, rel_widths = c(0.2, 0.4, 0.4))
})

p <- plot_grid(plotlist = plts, 
               nrow = length(plts),
               ncol = 1)
save_plot("cor_to_mucins_unbiased.pdf", 
          p,
          base_asp = 3,
          nrow = length(plts),
          ncol = 1)
p
write_csv(cor_values, "mucin_correlation_values.csv")
```

Examine SV40 WNT activity and genes correlated to gfp 

```{r}
p <- get_metadata(so_mucin, c("egfp-sv40")) %>% 
  ggplot(aes(`egfp-sv40`, treatment)) +
    geom_density_ridges(aes(fill = treatment)) + 
  scale_fill_manual(values = palette_OkabeIto) +
  theme_ridges() +
  theme(legend.position = "none")
    

save_plot(file.path(fig_dir, "club_cells_wnt_egfp_sv40.pdf"), 
          p,
          base_asp = 1.4)
p
```

```{r}
genes_to_check <- rownames(so_mucin)[rowSums(so_mucin@assays$RNA@data > 0 ) > 5]
all_data <- get_metadata(so_mucin, genes_to_check, embedding = NULL) %>% 
  mutate(treatment = factor(treatment, levels = c("Saline", "Elastase"))) %>% 
  filter(`egfp-sv40` > 0)

elast <- filter(all_data, treatment == "Elastase")
saline <- filter(all_data, treatment == "Saline")

cor_values <- map_dfr(to_check, ~{
  tibble(
    gene = .x,
    elastase_muc5b = cor(elast[[.x]], elast[["egfp-sv40"]], method = "spearman"),
    saline_muc5b = cor(saline[[.x]], saline[["egfp-sv40"]], method = "spearman"))
  }) %>% 
  arrange(desc(elastase_muc5b)) 


plts <- map(cor_values$gene[2:11], ~{
  
  bplot <- ggplot(all_data, aes_string("treatment", .x)) +
    geom_boxplot(aes(fill = treatment)) +
    geom_jitter() +
    scale_fill_manual(values = palette_OkabeIto) +
    labs(x = "") +
    theme(legend.position = "none")
    
  
  splts <- map(c("egfp-sv40"),
      function(x){
        ecor <- cor(elast[[.x]], elast[[x]], method = "spearman")
        scor <- cor(saline[[.x]], saline[[x]], method = "spearman")
        
        text_df <- tibble(
          treatment = factor(c("Saline", "Elastase"),levels = c("Saline", "Elastase")),
          pearson = str_c("r = ", signif(c(scor, ecor), 3))
        )
        p <- ggplot(all_data, aes_string(.x, paste0("`", x, "`"))) +
          geom_point(aes(color = treatment)) +
          facet_wrap(~treatment) +
          geom_text(data = text_df,
                    aes(x = -Inf, y = -Inf, label = pearson),
                    hjust   = -.5,
                    vjust   = -20) +
          scale_color_manual(values = palette_OkabeIto) +
    theme(legend.position = "none")
        p
      })
  plot_grid(plotlist = c(list(bplot), splts),
            ncol = 3,
            nrow = 1, rel_widths = c(0.2, 0.4, 0.4))
})

p <- plot_grid(plotlist = plts, 
               nrow = length(plts),
               ncol = 1)
save_plot("cor_to_wnt_reporter.pdf", 
          p,
          base_asp = 3,
          nrow = length(plts),
          ncol = 1)
p

cor_values %>% 
  dplyr::rename(elastase_wnt_reporter = elastase_muc5b,
                saline_wnt_reporter = saline_muc5b) %>% 
write_csv(., "wnt_reporter_correlation_values.csv")
```
